baseURL: "https://Siyuan-Shen.github.io" 
title: Siyuan Shen
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About Me
          url: aboutme/
          weight: 1
        - name: Research
          url: research/
          weight: 2
        - name: Publications
          url: papers/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: CV
          url: Resume_SiyuanShen.pdf
          weight: 6

params:
    description: "This website hosts Siyuan Shen's research papers, data, curriculum vitae, and contact information."
    author: Siyuan Shen
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["About Me","courses","publications","data"] #"Research"
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Siyuan Shen
          subtitle: "I am a PhD candidate in the department of Energy, Environmental & Chemical Engineering at the Washington University in St. Louis. My research is dedicated to applying deep learning methods to uncover new perspectives on air quality, satellite image-based retrievals, and climate-aerosol interactions. I am also willing to explore the interactions between air quality, anthropogenic activities, climate change and public health. "
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me
              url: aboutme/
            #- name: Research
            #  url: research/
            - name: Publications
              url: papers/
            - name: Data
              url: data/
            - name: CV
              url: Resume_SiyuanShen.pdf


    socialIcons:
        - name: CV
          url: Resume_SiyuanShen.pdf
        - name: Email
          url: mailto:s.siyuan@wustl.edu
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=Fu3wP14AAAAJ
        - name: GitHub
          url: https://github.com/Siyuan-Shen
        - name: LinkedIn
          url: https://www.linkedin.com/in/siyuan-shen-68019b1a6/
        - name: Twitter
          url: https://x.com/ShenSiyuanA
        - name: Other
          url: https://www.satpm.org/
        - name: Other
          url: https://www.atmoschemml.com/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Siyuan Shen"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2